import React, { useEffect, useState } from 'react'
import AdminLayout from '@/components/layout/AdminLayout'
import Container from '@mui/material/Container'
import Box from '@mui/material/Box'
import Typography from '@mui/material/Typography'
import Grid from '@mui/material/Grid'
import TextField from '@mui/material/TextField'
import Button from '@mui/material/Button'
import Paper from '@mui/material/Paper'
import IconButton from '@mui/material/IconButton'
import DeleteIcon from '@mui/icons-material/Delete'
import EditIcon from '@mui/icons-material/Edit'
import Snackbar from '@mui/material/Snackbar'
import Alert from '@mui/material/Alert'
import Card from '@mui/material/Card'
import CardMedia from '@mui/material/CardMedia'
import CardContent from '@mui/material/CardContent'
import Chip from '@mui/material/Chip'

type HomepageSlide = {
  id?: number
  title: string
  highlightedWord: string
  subtitle: string
  image: string
  sortOrder: number
  createdAt?: string
}

const AdminHomepageSlides = () => {
  const [slides, setSlides] = useState<HomepageSlide[]>([])
  const [form, setForm] = useState<HomepageSlide>({ 
    title: '', 
    highlightedWord: '', 
    subtitle: '', 
    image: '', 
    sortOrder: 0 
  })
  const [editingId, setEditingId] = useState<number | null>(null)
  const [snackbar, setSnackbar] = useState({
    open: false,
    message: '',
    severity: 'success' as 'success' | 'error' | 'info' | 'warning'
  })

  const load = async () => {
    try {
      // For now, we'll use sample data. In a real app, this would fetch from API
      const sampleSlides: HomepageSlide[] = [
        {
          id: 1,
          title: 'Welcome to',
          highlightedWord: 'JayPee Digital',
          subtitle: 'Your gateway to digital learning and excellence',
          image: '/images/slide1.jpg',
          sortOrder: 1,
          createdAt: new Date().toISOString()
        },
        {
          id: 2,
          title: 'Discover',
          highlightedWord: 'Innovation',
          subtitle: 'Cutting-edge courses and resources for modern learners',
          image: '/images/slide2.jpg',
          sortOrder: 2,
          createdAt: new Date().toISOString()
        }
      ]
      setSlides(sampleSlides)
    } catch (error) {
      console.error('Failed to load homepage slides:', error)
      setSnackbar({
        open: true,
        message: 'Failed to load homepage slides',
        severity: 'error'
      })
    }
  }

  useEffect(() => { 
    load()
  }, [])

  const submit = async () => {
    try {
      if (editingId) {
        // Update existing slide
        const updatedSlides = slides.map(slide => 
          slide.id === editingId 
            ? { ...form, id: editingId }
            : slide
        )
        setSlides(updatedSlides)
        setSnackbar({
          open: true,
          message: 'Homepage slide updated successfully',
          severity: 'success'
        })
      } else {
        // Add new slide
        const newSlide = {
          ...form,
          id: Date.now(), // In real app, this would be generated by the backend
          createdAt: new Date().toISOString()
        }
        setSlides([...slides, newSlide])
        setSnackbar({
          open: true,
          message: 'Homepage slide created successfully',
          severity: 'success'
        })
      }
      
      setForm({ 
        title: '', 
        highlightedWord: '', 
        subtitle: '', 
        image: '', 
        sortOrder: 0 
      })
      setEditingId(null)
    } catch (error) {
      console.error('Error saving homepage slide:', error)
      setSnackbar({
        open: true,
        message: 'Failed to save homepage slide',
        severity: 'error'
      })
    }
  }

  const edit = (slide: HomepageSlide) => {
    setEditingId(slide.id!)
    setForm({ 
      title: slide.title, 
      highlightedWord: slide.highlightedWord, 
      subtitle: slide.subtitle, 
      image: slide.image, 
      sortOrder: slide.sortOrder 
    })
  }

  const remove = async (id: number) => {
    try {
      const updatedSlides = slides.filter(slide => slide.id !== id)
      setSlides(updatedSlides)
      setSnackbar({
        open: true,
        message: 'Homepage slide deleted successfully',
        severity: 'success'
      })
    } catch (error) {
      console.error('Error deleting homepage slide:', error)
      setSnackbar({
        open: true,
        message: 'Failed to delete homepage slide',
        severity: 'error'
      })
    }
  }

  const handleCloseSnackbar = () => {
    setSnackbar({ ...snackbar, open: false })
  }

  return (
    <Box sx={{ py: 6 }}>
      <Container maxWidth="lg">
        <Typography variant="h4" sx={{ mb: 3, fontWeight: 700 }}>Manage Homepage Slides</Typography>

        <Paper sx={{ p: 3, mb: 4 }}>
          <Typography variant="h6" sx={{ mb: 2 }}>
            {editingId ? 'Edit Homepage Slide' : 'Add New Homepage Slide'}
          </Typography>
          <Grid container spacing={3}>
            <Grid item xs={12} md={6}>
              <TextField 
                fullWidth 
                label="Title" 
                value={form.title} 
                onChange={(e) => setForm({ ...form, title: e.target.value })} 
                required
                helperText="Main title text (e.g., 'Welcome to')"
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField 
                fullWidth 
                label="Highlighted Word" 
                value={form.highlightedWord} 
                onChange={(e) => setForm({ ...form, highlightedWord: e.target.value })} 
                required
                helperText="Word or phrase to highlight (e.g., 'JayPee Digital')"
              />
            </Grid>
            <Grid item xs={12}>
              <TextField 
                fullWidth 
                label="Subtitle" 
                value={form.subtitle} 
                onChange={(e) => setForm({ ...form, subtitle: e.target.value })} 
                required
                helperText="Descriptive subtitle text"
              />
            </Grid>
            <Grid item xs={12} md={8}>
              <TextField 
                fullWidth 
                label="Image URL" 
                value={form.image} 
                onChange={(e) => setForm({ ...form, image: e.target.value })} 
                required
                helperText="URL or path to the slide background image"
              />
            </Grid>
            <Grid item xs={12} md={4}>
              <TextField 
                type="number" 
                fullWidth 
                label="Sort Order" 
                value={form.sortOrder} 
                onChange={(e) => setForm({ ...form, sortOrder: Number(e.target.value) })} 
                helperText="Display order (lower numbers first)"
              />
            </Grid>
            <Grid item xs={12}>
              <Button variant="contained" onClick={submit} size="large">
                {editingId ? 'Update Slide' : 'Create Slide'}
              </Button>
              {editingId && (
                <Button 
                  variant="outlined" 
                  onClick={() => {
                    setEditingId(null)
                    setForm({ 
                      title: '', 
                      highlightedWord: '', 
                      subtitle: '', 
                      image: '', 
                      sortOrder: 0 
                    })
                  }}
                  sx={{ ml: 2 }}
                >
                  Cancel
                </Button>
              )}
            </Grid>
          </Grid>
        </Paper>

        <Paper sx={{ p: 3 }}>
          <Typography variant="h6" sx={{ mb: 2 }}>Homepage Slides</Typography>
          {slides.length === 0 ? (
            <Typography color="text.secondary">No homepage slides found. Create your first slide!</Typography>
          ) : (
            <Grid container spacing={3}>
              {slides
                .sort((a, b) => a.sortOrder - b.sortOrder)
                .map((slide) => (
                <Grid item xs={12} md={6} lg={4} key={slide.id}>
                  <Card sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
                    <CardMedia
                      component="img"
                      height="200"
                      image={slide.image}
                      alt={slide.title}
                      sx={{ objectFit: 'cover' }}
                      onError={(e) => {
                        // Fallback to placeholder if image fails to load
                        (e.target as HTMLImageElement).src = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZGRkIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxNCIgZmlsbD0iIzk5OSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZHk9Ii4zZW0iPkltYWdlIG5vdCBmb3VuZDwvdGV4dD48L3N2Zz4='
                      }}
                    />
                    <CardContent sx={{ flexGrow: 1, display: 'flex', flexDirection: 'column' }}>
                      <Box sx={{ flexGrow: 1 }}>
                        <Typography variant="h6" sx={{ mb: 1 }}>
                          {slide.title} <span style={{ color: 'primary.main', fontWeight: 'bold' }}>{slide.highlightedWord}</span>
                        </Typography>
                        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                          {slide.subtitle}
                        </Typography>
                        <Box sx={{ display: 'flex', gap: 1, mb: 2 }}>
                          <Chip 
                            label={`Order: ${slide.sortOrder}`} 
                            size="small" 
                            variant="outlined" 
                          />
                          {slide.createdAt && (
                            <Chip 
                              label={`Created: ${new Date(slide.createdAt).toLocaleDateString()}`} 
                              size="small" 
                              variant="outlined" 
                            />
                          )}
                        </Box>
                      </Box>
                      <Box sx={{ display: 'flex', justifyContent: 'flex-end', gap: 1 }}>
                        <IconButton onClick={() => edit(slide)} color="primary" size="small">
                          <EditIcon />
                        </IconButton>
                        <IconButton color="error" onClick={() => remove(slide.id!)} size="small">
                          <DeleteIcon />
                        </IconButton>
                      </Box>
                    </CardContent>
                  </Card>
                </Grid>
              ))}
            </Grid>
          )}
        </Paper>

        {/* Snackbar for notifications */}
        <Snackbar
          open={snackbar.open}
          autoHideDuration={6000}
          onClose={handleCloseSnackbar}
        >
          <Alert 
            onClose={handleCloseSnackbar} 
            severity={snackbar.severity}
          >
            {snackbar.message}
          </Alert>
        </Snackbar>
      </Container>
    </Box>
  )
}

AdminHomepageSlides.getLayout = (page: React.ReactElement) => <AdminLayout title="Manage Homepage Slides" breadcrumbs={[{ label: 'Homepage Slides' }]}>{page}</AdminLayout>

export default AdminHomepageSlides