import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/9789350906576.png',
    title: 'Forensic Medicine and Toxicology for Medical Students',
    rating: 5,
    ratingCount: 8,
    contenttype: 'books',
    subjectcategory: 'medicine',
  },
  {
    id: 2,
    cover: '/images/courses/9789352501915.png',
    title: 'Forensic Medicine and Toxicology for Medical Students',
    rating: 5,
    ratingCount: 15,
    contenttype: 'books',
    subjectcategory: 'dentistry',
  },
  {
    id: 3,
    cover: '/images/courses/9789352707010.png',
    title: 'Mastering Data Modeling Fundamentals',
    rating: 4,
    ratingCount: 7,
    contenttype: 'books',
    subjectcategory: 'nursing',
  },
  {
    id: 4,
    cover: '/images/courses/jaypee-BPJ.JPG',
    title: 'Medical MCQs Practice Set',
    rating: 4,
    ratingCount: 12,
    contenttype: 'mcqs',
    subjectcategory: 'medicine',
  },
  {
    id: 5,
    cover: '/images/courses/jaypee-DJAS.JPG',
    title: 'Modern React with MUI & Redux',
    rating: 4,
    ratingCount: 32,
    contenttype: 'journals',
    subjectcategory: 'dentistry',
  },
  {
    id: 6,
    cover: '/images/courses/jaypee-DSJUOG.JPG',
    title: 'Clinical Case Studies Collection',
    rating: 5,
    ratingCount: 14,
    contenttype: 'cases',
    subjectcategory: 'nursing',
  },
  {
    id: 7,
    cover: '/images/courses/Video01.JPG',
    title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
    rating: 4,
    ratingCount: 6,
    contenttype: 'videos',
    subjectcategory: 'medicine',
  },
  {
    id: 8,
    cover: '/images/courses/9789354652974.png',
    title: 'Forensic Medicine and Toxicology for Medical Students',
    rating: 5,
    ratingCount: 8,
    contenttype: 'books',
    subjectcategory: 'medicine',
  },
  {
    id: 9,
    cover: '/images/courses/9789354659508.png',
    title: 'Forensic Medicine and Toxicology for Medical Students',
    rating: 5,
    ratingCount: 15,
    contenttype: 'books',
    subjectcategory: 'dentistry',
  },
  {
    id: 10,
    cover: '/images/courses/9789356962026.png',
    title: 'Mastering Data Modeling Fundamentals',
    rating: 4,
    ratingCount: 7,
    contenttype: 'books',
    subjectcategory: 'nursing',
  },
  {
    id: 11,
    cover: '/images/courses/jaypee-IJCCM.JPG',
    title: 'The Complete Guide Docker and Kubernetes',
    rating: 4,
    ratingCount: 12,
    contenttype: 'journals',
    subjectcategory: 'medicine',
  },
  {
    id: 12,
    cover: '/images/courses/jaypee-IJCPD.JPG',
    title: 'Modern React with MUI & Redux',
    rating: 4,
    ratingCount: 32,
    contenttype: 'journals',
    subjectcategory: 'dentistry',
  },
  {
    id: 13,
    cover: '/images/courses/jaypee-IJESR.JPG',
    title: 'Ethical Hacking Bootcamp Zero to Mastery',
    rating: 5,
    ratingCount: 14,
    contenttype: 'journals',
    subjectcategory: 'nursing',
  },
  {
    id: 14,
    cover: '/images/courses/video-40b.PNG',
    title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
    rating: 4,
    ratingCount: 6,
    contenttype: 'videos',
    subjectcategory: 'dentistry',
  },
  {
    id: 15,
    cover: '/images/courses/9789356962965.png',
    title: 'Forensic Medicine and Toxicology for Medical Students',
    rating: 5,
    ratingCount: 8,
    contenttype: 'books',
    subjectcategory: 'medicine',
  },
  {
    id: 16,
    cover: '/images/courses/9789356963344.png',
    title: 'Forensic Medicine and Toxicology for Medical Students',
    rating: 5,
    ratingCount: 15,
    contenttype: 'books',
    subjectcategory: 'dentistry',
  },
  {
    id: 17,
    cover: '/images/courses/9789356966338.png',
    title: 'Mastering Data Modeling Fundamentals',
    rating: 4,
    ratingCount: 7,
    contenttype: 'books',
    subjectcategory: 'nursing',
  },
  {
    id: 18,
    cover: '/images/courses/jaypee-IJKECD.JPG',
    title: 'The Complete Guide Docker and Kubernetes',
    rating: 4,
    ratingCount: 12,
    contenttype: 'journals',
    subjectcategory: 'medicine',
  },
  {
    id: 19,
    cover: '/images/courses/jaypee-JCDP.JPG',
    title: 'Modern React with MUI & Redux',
    rating: 4,
    ratingCount: 32,
    contenttype: 'journals',
    subjectcategory: 'dentistry',
  },
  {
    id: 20,
    cover: '/images/courses/jaypee-JOGI.JPG',
    title: 'Ethical Hacking Bootcamp Zero to Mastery',
    rating: 5,
    ratingCount: 14,
    contenttype: 'journals',
    subjectcategory: 'nursing',
  },
  {
    id: 21,
    cover: '/images/courses/video2.JPG',
    title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
    rating: 4,
    ratingCount: 6,
    contenttype: 'videos',
    subjectcategory: 'nursing',
  },
  {
    id: 22,
    title: 'Advanced Medical Diagnostics',
    cover: '/images/courses/course-22.jpg',
    rating: 4.8,
    ratingCount: 156,
    contenttype: 'books',
    subjectcategory: 'medicine',
  },
  {
    id: 25,
    title: 'Clinical Pathology Handbook',
    cover: '/images/courses/course-25.jpg',
    rating: 4.7,
    ratingCount: 203,
    contenttype: 'books',
    subjectcategory: 'medicine',
  },
  {
    id: 26,
    title: 'Surgical Techniques and Procedures',
    cover: '/images/courses/course-26.jpg',
    rating: 4.9,
    ratingCount: 178,
    contenttype: 'books',
    subjectcategory: 'medicine',
  },
  {
    id: 28,
    title: 'Advanced Medical Video Series',
    cover: '/images/courses/course-28.jpg',
    rating: 4.6,
    ratingCount: 142,
    contenttype: 'videos',
    subjectcategory: 'medicine',
  },
  {
    id: 30,
    title: 'International Medical Journal Collection',
    cover: '/images/courses/course-30.jpg',
    rating: 4.8,
    ratingCount: 267,
    contenttype: 'journals',
    subjectcategory: 'medicine',
  },
]